# Traefik Static Configuration Reference
# Link: https://doc.traefik.io/traefik/reference/static-configuration/file/

[global]
    checkNewVersion = false
    sendAnonymousUsage = true

[api]
    # insecure = true
    dashboard = true
    debug = true

[metrics]
    [metrics.influxDB]
        address = "http://influxdb:8086"
        protocol = "http"
        pushInterval = "42s"
        # Same as that of the environment file
        database = "edge"
        username = "tiguitto"
        password = "tiguitto"
        addEntryPointsLabels = true
        addServicesLabels = true

[log]
    level = "DEBUG"

[accessLog]
    filePath = "/log/access.log"
    bufferingSize = 100
    [accessLog.filters]
        statusCodes = ["200", "300-302", "400-499"]
        retryAttempts = true
        minDuration = 10

[entryPoints]
    [entryPoints.web]
        address = ":80"
    [entryPoints.mqtt]
        address = ":1883"
    [entryPoints.websockets]
        address = ":1884"

[providers]
    [providers.docker]
        endpoint = "unix:///var/run/docker.sock"
        exposedByDefault = false
        network = "iotstack"
    [providers.file]
        directory = "/etc/traefik/configurations/"
        watch = true